import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const noto = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={noto.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
